### ISSUE TITLE
Feature Request for Android: Please request camera permission on first app start

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/mlkit#13]
If I run the plugin on IOS, the first time I start the app, it automatically asks me for camera permissions. On Android, it does not ask for permission. Would be great if it would be the same behavior on both platforms. Ideally should ask on first start on both platforms.

**Comment by triniwiz** [comment]
I plan to turn it off by default an leave that up to the dev

**Comment by cjohn001** [comment]
@triniwiz : Ok, I would prefer to have it requested, as the request is always needed. However, as long as the behavior is identical it is good.
