### ISSUE TITLE
iOS & Android bug: Please fix difference in signature of onDetection method

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/mlkit#21]
The (detection)="OnDetection($event)" method has different signature when called on Android and on IOS.  On Android the barcode is an object which was serialized as a string, on iOS it is a javascript object, see screenshots below. 

iOS:
<img width="341" alt="iosEvent" src="https://user-images.githubusercontent.com/43253483/147134609-8d1fb2cf-0836-46ed-8929-f59c33c2a5ef.png">

Android:

<img width="398" alt="androidEvent" src="https://user-images.githubusercontent.com/43253483/147134655-5ddb6a5e-2fe6-46c1-aa3b-8d08e221782d.png">

It would be great to have the iOS variant (javascript object) consistently on both platforms. It would also be great to have typescript typings for the entire barcode object in the event. Currently, the type is simply data: { [key: string]: any };

**Comment by triniwiz** [comment]
That's a bug the return value should be any array of objects not strings

**Comment by kriefsacha** [comment]
Same here, tested on android, data is type

> data: { [key: string]: any };
