### ISSUE TITLE
iOS only - image rotation on latestImage

### ISSUE THREAD

**Issue by kriefsacha** [NativeScript/mlkit#29]
Hi,

On the last version of nativescript, of the plugin and of iOS the latest image of the MLKitView is in landscape orientation.

I tried to turn it manually but i found only android code, which in android it works.

Thats how i take the image

` let source = (this.faceDetectorRef.nativeElement as MLKitView).latestImage;`

Thank you

**Comment by kriefsacha** [comment]
@triniwiz there is a chance you take a look at this ?

**Comment by triniwiz** [comment]
Should be fixed in e6c694cad935dd799c722a377b9dabff9d8049aa
