### ISSUE TITLE
Android - issue w/ setProcessEveryNthFrame

### ISSUE THREAD

**Issue by DanielDent** [NativeScript/mlkit#33]
I have an application which works fine on iOS, but crashes on Android. I get the following error:

JS: [Vue warn]: Error in nextTick: "TypeError: __classPrivateFieldGet(...).setProcessEveryNthFrame is not a function"

Was Android tested when support for setProcessEveryNthFrame was added?

**Comment by DanielDent** [comment]
I have further details about this crash: it seems to occur specifically when processEveryNthFrame gets attached to a variable, and that variable is changed. I.e. in Vue, `:processEveryNthFrame="testVariable"`, and then testVariable is mutated.

**Comment by DanielDent** [comment]
I am mistaken about my prior comment, this crash seems to still occur even if testVariable is not mutated.

**Comment by DanielDent** [comment]
For what it's worth, when I tried removing setProcessEveryNthFrame from the app entirely, the build ran on Android, but did not detect any barcodes. The exact same codebase on iOS works great.

**Comment by brooklax** [comment]
@DanielDent were you able to find a workaround or resolve the issue? it seems that adding the "setProcessEveryNthFrame" prop improves barcode scanner accuracy but it's still resulting in a crash when the prop is added on android.

We're using:

"@nativescript/mlkit-barcode-scanning": "^1.0.6",
"@nativescript/mlkit-core": "^1.0.6",
"@nativescript/android": "8.4.0",
"@nativescript/ios": "8.4.0",
"nativescript-vue": "^2.9.3",

**Comment by devlinpadayachee** [comment]
Anybody found a workaround?

**Comment by triniwiz** [comment]
Finally got change to fix this so it now works in the latest release, thanks for reporting.

**Comment by brooklax** [comment]
@triniwiz apologies but I just tested with a new android build on my side and although I don't get an exception anymore like before, it also seems like adding the property now results in no results returned for the detection event. When I remove the property scanning works but it's not accurate with Code39 barcode types especially.

<MLKitView
        cameraPosition="back"
        :detectionType="type || 'all'"
        :barcodeFormats="formats"
        :processEveryNthFrame="60"
        @detection="onScanResult"
        :pause="pauseScanner"
        :torchOn="torchOn"
      />

**Comment by brooklax** [comment]
Sorry I see this issue is closed, will open a new one

**Comment by devlinpadayachee** [comment]
> @triniwiz apologies but I just tested with a new android build on my side and although I don't get an exception anymore like before, it also seems like adding the property now results in no results returned for the detection event. When I remove the property scanning works but it's not accurate with Code39 barcode types especially.
> 
> <MLKitView cameraPosition="back" :detectionType="type || 'all'" :barcodeFormats="formats" :processEveryNthFrame="60" @detection="onScanResult" :pause="pauseScanner" :torchOn="torchOn" />

+1

**Comment by devlinpadayachee** [comment]
Any updates?

**Comment by triniwiz** [comment]
Nothing yet, but I'll look into it soon
